server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /playground {
        return 301 /playground/;
    }

    location /playground/ {
        alias /usr/share/nginx/html/playground/;
        try_files $uri $uri/ /playground/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
